#twitter oAuth tokens get your own here : https://apps.twitter.com
ACCESS_TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ACCESS_TOKEN_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 
CONSUMER_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CONSUMER_KEY_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"